### ISSUE TITLE
Add example code

### ISSUE THREAD

**Issue by dhanekom** [HashLoad/DMFBr#1]
First off, thank you for the effort you have put into this project. I have read though all the docs here https://dmfbr-en.docs-br.com/ but I think I am still misunderstanding a few concepts. From what a gather a module can be used to logically group code (classes) for a concept (e.g. a controller, view and models for user login functionality) and the module can be swopped out for e.g. a module to test user login functionality that uses dependency injection to instantiate test code. Do I understand the main concept?

I have tried to put together a working demo from the code snippets in your docs but I must be doing something wrong. Can you please add some demo projects with full source code (that includes e.g. a basic controller and view)? The docs are written from the perspective of someone who will using DMFBr as a web server but can you please add examples to use it in a web server and in a VCL application?

**Comment by isaquepinheiro** [comment]
> First off, thank you for the effort you have put into this project. I have read though all the docs here https://dmfbr-en.docs-br.com/ but I think I am still misunderstanding a few concepts. From what a gather a module can be used to logically group code (classes) for a concept (e.g. a controller, view and models for user login functionality) and the module can be swopped out for e.g. a module to test user login functionality that uses dependency injection to instantiate test code. Do I understand the main concept?
> 
> I have tried to put together a working demo from the code snippets in your docs but I must be doing something wrong. Can you please add some demo projects with full source code (that includes e.g. a basic controller and view)? The docs are written from the perspective of someone who will using DMFBr as a web server but can you please add examples to use it in a web server and in a VCL application?

First of all, thank you for your interest and feedback. Your understanding is correct, the concept of ModularBr was based on the concept of NestJS. We are working to provide demos. Please continue to follow the project as we are implementing new features such as Pipes, which will be useful in our daily work. Soon, we will also have the DMFBr CLI, which is currently in my personal repository. Once the version is more stable, we will move it to HashLoad.

**Comment by isaquepinheiro** [comment]
> First off, thank you for the effort you have put into this project. I have read though all the docs here https://dmfbr-en.docs-br.com/ but I think I am still misunderstanding a few concepts. From what a gather a module can be used to logically group code (classes) for a concept (e.g. a controller, view and models for user login functionality) and the module can be swopped out for e.g. a module to test user login functionality that uses dependency injection to instantiate test code. Do I understand the main concept?
> 
> I have tried to put together a working demo from the code snippets in your docs but I must be doing something wrong. Can you please add some demo projects with full source code (that includes e.g. a basic controller and view)? The docs are written from the perspective of someone who will using DMFBr as a web server but can you please add examples to use it in a web server and in a VCL application?

https://github.com/HashLoad/DMFBr/tree/main/Exemples/vcl

**Comment by isaquepinheiro** [comment]
Add exemple
