### ISSUE TITLE
CLI or wizzard to create boilerplate code

### ISSUE THREAD

**Issue by dhanekom** [HashLoad/DMFBr#2]
To improve developer experience, reduce code to write, and improve code consistency I would like to suggest that a CLI or wizard be added to create boilerplate module folders and code.

Here is a suggestion of how it could work:

CLI:
- Run the CLI from the application root directory
- The CLI can have a built in set of module structure templates from which it can generate code
- Possible command line options:
-- templates (shows a list of templates that can be used and a)
-- add <template> <module name> (create folders and files based on the selected template and module name)
- Have the ability to configure custom templates in a dmfbr config file in the project root

**Comment by isaquepinheiro** [comment]
Thank you for the feedback. I will take your suggestion into consideration.
At the moment, you can edit the existing templates as per your requirements.

**Comment by isaquepinheiro** [comment]
> To improve developer experience, reduce code to write, and improve code consistency I would like to suggest that a CLI or wizard be added to create boilerplate module folders and code.
> 
> Here is a suggestion of how it could work:
> 
> CLI:
> 
> * Run the CLI from the application root directory
> * The CLI can have a built in set of module structure templates from which it can generate code
> * Possible command line options:
>   -- templates (shows a list of templates that can be used and a)
>   -- add   (create folders and files based on the selected template and module name)
> * Have the ability to configure custom templates in a dmfbr config file in the project root

Thank you for the feedback. I will take your suggestion into consideration.
At the moment, you can edit the existing templates as per your requirements.

**Comment by isaquepinheiro** [comment]
![image](https://github.com/HashLoad/DMFBr/assets/4005289/4ab074ac-9149-4bc0-b812-a86edf80ae42)

**Comment by dhanekom** [comment]
Thank you @isaquepinheiro . Apologies, I did not even know https://github.com/isaquepinheiro/dmfbr_cli existed... I will take a look at dmfbr_cli . Thank you for your quick response.
